// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherAPI.Data;

#nullable disable

namespace WeatherAPI.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20260811112924_SeedWeatherData")]
    partial class SeedWeatherData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherAPI.Models.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxTemperature")
                        .HasColumnType("int");

                    b.Property<int>("MinTemperature")
                        .HasColumnType("int");

                    b.Property<string>("NextDayOutlook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WindDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WindSpeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Dublin",
                            CurrentCondition = "cloudy",
                            MaxTemperature = 18,
                            MinTemperature = 11,
                            NextDayOutlook = "rain",
                            WindDirection = "southwest",
                            WindSpeed = 25
                        },
                        new
                        {
                            Id = 2,
                            City = "London",
                            CurrentCondition = "rain",
                            MaxTemperature = 16,
                            MinTemperature = 9,
                            NextDayOutlook = "cloudy",
                            WindDirection = "west",
                            WindSpeed = 30
                        },
                        new
                        {
                            Id = 3,
                            City = "Paris",
                            CurrentCondition = "sunny",
                            MaxTemperature = 23,
                            MinTemperature = 14,
                            NextDayOutlook = "cloudy",
                            WindDirection = "south",
                            WindSpeed = 15
                        },
                        new
                        {
                            Id = 4,
                            City = "New York",
                            CurrentCondition = "sunny",
                            MaxTemperature = 28,
                            MinTemperature = 20,
                            NextDayOutlook = "overcast",
                            WindDirection = "east",
                            WindSpeed = 18
                        },
                        new
                        {
                            Id = 5,
                            City = "Sydney",
                            CurrentCondition = "cloudy",
                            MaxTemperature = 21,
                            MinTemperature = 15,
                            NextDayOutlook = "sunny",
                            WindDirection = "southeast",
                            WindSpeed = 20
                        },
                        new
                        {
                            Id = 6,
                            City = "Tokyo",
                            CurrentCondition = "rain",
                            MaxTemperature = 24,
                            MinTemperature = 18,
                            NextDayOutlook = "drizzle",
                            WindDirection = "northeast",
                            WindSpeed = 22
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
